### ISSUE TITLE
🚧 **Apply fixes and patches from pivx source** 🚧

### ISSUE THREAD

**Issue by WagerrTor** [wagerr/wagerr#22]
We need to review all fixes and patches all the time. In this project we will apply all fixes and patches up to 28. Feb.
- [x] Create a list of patches
- [x] Create project
- [ ] Create card for each patch if not applied with info about the reason
- [x] Apply all patches

**Comment by WagerrTor** [comment]
We will review and apply all patches from PIVX until now.

@Assigners & @Contributors
To get all patches since our fork, please git clone [PIVX sources](https://github.com/PIVX-Project/PIVX) run `git format-patch -n 9e2ed8f0f838ae7659487f256a153de66ca5a7a7` and they will be stored in the folder you run this command from. We need to review them all if and why are they to be applied (or not).

here is a list of all, this list will be edited if patches get applied.

- [x] 0001-Add-old-signals-from-main-and-mark-unused-signals-wi.patch (#27)
- [x] 0002-Remove-old-g_signals-code-and-replace-with-GetMainSi.patch (#27)
- [x] 0003-Add-GetMainSignals-events-to-Miner-and-SwiftX.patch (#27)
- [x] 0004-Add-time-offset-to-peer-data.patch
- [x] 0005-Display-netmasks-as-bits-instead-of-strings.patch
- [x] 0006-Refactor-node-banning-functions.patch
- [x] 0007-clear-selected-peer-when-switching-away-from-peers-t.patch
- [x] 0008-Introduce-and-hook-up-the-bantablemodel.patch
- [x] 0009-Remove-potentional-memory-leak-update-multisend-code.patch
- [x] 0010-Build-compile-link-winshutdownmonitor.cpp-on-Windows.patch
- [x] 0011-UI-Rework-of-overview-page.patch
- [x] 0012-Refactor-Moved-wallet-balance-computation-from-heade.patch
- [x] 0013-Fixed-Dynamic-Screen-Elements-Issue.patch
- [x] 0014-Add-Labels-to-MultiSend-GUI.patch
- [x] 0015-wallet-Fix-a-bug-where-autocombinerewards-was-genera.patch
- [x] 0016-RPC-show-script-verification-errors-in-signrawtransa.patch (#30)
- [x] 0017-Optimisation-backport-of-3e7c89196c.patch
- [x] 0018-Refactor-Factor-out-function-ComputeTimeSmart-for-TX.patch
- [x] 0019-UI-Send-popup-simplified-SwiftTX-SwiftX.patch
- [x] 0020-UI-Avoid-UTXO-split-send-message-addition-when-Split.patch
- [x] 0021-fix-paymentservertests.cpp-to-use-automatic-buffer-o.patch
- [x] 0022-Trivial-Update-casing-Pivx-to-PIVX-and-remove-Obfusc.patch
- [x] 0023-UI-Autoscroll-to-end-of-zPIV-status-output.patch
- [x] 0024-core-Fix-masternode-broadcast-for-networks-MAINNET-u.patch
- [x] 0025-Performance-AutocombineDust-is-called-less-often.patch
- [x] 0026-Remove-dupiclate-code.-Create-updateAddressBookLabel.patch
- [x] 0027-Wallet-Increase-fee-margin-to-up-to-10-of-autocombin.patch
- [x] 0028-libevent-based-httpd-server.patch
- [x] 0029-Update-REST-interface-to-allow-for-more-query-pathwa.patch
- [x] 0030-Make-getblockheader-RPC-return-more-information.patch
- [x] 0031-Move-windows-socket-init-to-utility-function.patch
- [x] 0032-Adjust-Qt-RPC-console-for-new-evhttpd-server.patch
- [x] 0033-Prepare-to-detach-rpcserver-from-main.h-dependency.patch
- [x] 0034-Get-rid-of-DetectShutdownThread.patch
- [x] 0035-Normalize-spacing-in-rpcprotocol.h.patch
- [x] 0036-init-Ignore-SIGPIPE.patch
- [x] 0037-init-add-new-debug-categories.patch
- [x] 0038-Update-contrib-manpage-example-files.patch
- [x] 0039-Core-Fix-wallet-repair-restart-exception.patch
- [x] 0040-Wallet-Combine-change-to-output-when-possible-provid.patch
- [x] 0041-Fix-crash-when-inputting-wrong-port-for-network-prox.patch
- [x] 0042-Qt-Additional-proxy-checks-in-options-dialog.patch
- [x] 0043-Trivial-Removing-useless-spaces.patch
- [x] 0044-Add-blocksizenotify-command.patch
- [x] 0045-Readme-changes.patch
- [x] 0046-Wallet-Fix-autocombine.patch
- [x] 0047-Depends-Update-depends-package-versions.patch
- [x] 0048-Qt-Remove-Growl-support.patch
- [x] 0049-Update-README.md.patch
- [x] 0050-Give-high-priority-to-zerocoinspends-to-make-it-into.patch
- [x] 0051-core-Minor-refacturing-unused-variable-removed.patch
- [x] 0052-Build-Update-build-system-from-upstream.patch (#23)
- [x] 0053-Fix-VLA-error-in-hash.h.patch (#23)
- [x] 0054-Use-and-define-strnlen-if-not-already-defined.patch (#23)
- [x] 0055-mac-update-macdeployqtplus-and-Info.plist.in.patch (#23)
- [x] 0056-build-Deduplicate-version-numbers.patch (#23)
- [x] 0057-osx-build-notes-libzmq-zmq-in-brew-install-add-libev.patch
- [x] 0058-travis-switch-to-minimal-travis-image.patch (#23)
- [x] 0059-Qt-Refactor-layouts-for-BIP38-Privacy-SendCoinsEntry.patch
- [x] 0060-Qt-add-a-paste-button-to-BIP38-s-decrypt-tab.patch
- [x] 0061-Qt-remove-instances-of-empty-placeholderText-propert.patch
- [x] 0062-Qt-BIP38-dialog-string-updates.patch
- [x] 0063-Qt-BIP38-return-decrypted-privkey-in-WIF-format.patch
- [x] 0064-Qt-Use-QToolButton-for-utility-buttons-in-MultiSig-U.patch
- [x] 0065-Qt-Make-Multisend-s-past-button-a-QToolButton.patch
- [x] 0066-Qt-Fix-warning-dialog-popup-for-the-Blockchain-Explo.patch
- [x] 0067-add-public-gpg-key.patch
- [x] 0068-Build-Fix-typo-in-Qt-test-makefile.patch
- [x] [0069-Remove-vfReachable-and-modify-IsReachable-to-only-us.patch](../commit/5ab3cc380680e498d0b77edad3d7b76c020fd496) (#7)
- [x] 0070-Refactor-ConnectBlock-to-segregate-state-tracking-it.patch
- [x] 0071-Allow-rpc-listunspent-to-have-options-for-watchonly-.patch
- [x] 0072-RPC-Segfault-pivx-cli-getinfo-while-loading-block-in.patch
- [x] 0073-Add-debug-info-for-CWallet-ReconsiderZerocoins.patch

**Comment by Cryptarchist** [comment]
At a minimum I am keen to bring in the patches that not only relate to PIVX, but are the upstream patches coming from Bitcoin or Dash.

I will focus on these patches initially:

**Update build system from upstream (#23)**
- [x] 0052-Build-Update-build-system-from-upstream.patch
- [x] 0053-Fix-VLA-error-in-hash.h.patch
- [x] 0054-Use-and-define-strnlen-if-not-already-defined.patch
- [x] 0055-mac-update-macdeployqtplus-and-Info.plist.in.patch
- [x] 0056-build-Deduplicate-version-numbers.patch
- [x] 0058-travis-switch-to-minimal-travis-image.patch

**Switch from local to main signals for the validation interface (#27)**
- [x] 0001-Add-old-signals-from-main-and-mark-unused-signals-wi.patch
- [x] 0002-Remove-old-g_signals-code-and-replace-with-GetMainSi.patch
- [x] 0003-Add-GetMainSignals-events-to-Miner-and-SwiftX.patch

**Show script verification errors in signrawtransaction result (#30)**
- [x] 0016-RPC-show-script-verification-errors-in-signrawtransa.patch

**Migrate to libevent based httpd server**
- [x] 0028-libevent-based-httpd-server.patch
- [x] 0029-Update-REST-interface-to-allow-for-more-query-pathwa.patch
- [x] 0030-Make-getblockheader-RPC-return-more-information.patch
- [x] 0031-Move-windows-socket-init-to-utility-function.patch
- [x] 0032-Adjust-Qt-RPC-console-for-new-evhttpd-server.patch
- [x] 0033-Prepare-to-detach-rpcserver-from-main.h-dependency.patch
- [x] 0034-Get-rid-of-DetectShutdownThread.patch
- [x] 0035-Normalize-spacing-in-rpcprotocol.h.patch
- [x] 0036-init-Ignore-SIGPIPE.patch
- [x] 0037-init-add-new-debug-categories.patch
- [x] 0038-Update-contrib-manpage-example-files.patch
- [x] 0039-Core-Fix-wallet-repair-restart-exception.patch
